---
- hosts: all
  tasks:
    - name: Init archlinux keyring
      shell:
        cmd: "{{ item }}"
      with_items:
        - pacman-key --init
        - pacman-key --populate
        - pacman -Sy --noconfirm

    - name: Delete conflicting packages
      pacman:
        name: iptables
        state: absent
        force: true

    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - lxd
        - python-setuptools
        - python-pip
        - gcc

    - name: Setup unprivileges containers
      blockinfile:
        state: present
        insertafter: EOF
        dest: /etc/lxc/default.conf
        marker: "# {mark} added by ansible"
        block: |
          lxc.idmap = u 0 100000 65536
          lxc.idmap = g 0 100000 65536

    - name: Setup subuid
      copy:
        dest: "{{ item }}"
        content: "root:100000:65536"
      loop:
        - /etc/subuid
        - /etc/subgid

    - name: Start lxd service
      systemd:
        name: lxd
        enabled: true
        state: started

    - name: Init lxd
      shell: lxd init --auto

    - name: Clone lxdui
      git:
        dest: /root/lxdui
        repo: https://github.com/AdaptiveScale/lxdui.git

    - name: Install lxdui
      shell:
        chdir: /root/lxdui
        cmd: python3 setup.py install

    - name: Run lxdui
      shell:
        chdir: /root/lxdui
        cmd: nohup lxdui start </dev/null >/dev/null 2>&1 &
